FROM node:22-slim

WORKDIR /app

COPY package*.json ./
COPY .env.development ./
RUN npm install
RUN npm install -g ts-node-dev

COPY . .

RUN npm run prisma:generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]