FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY .env.development ./
RUN npm install

COPY . .

RUN npm run prisma:generate

EXPOSE 3000

CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"]