services:
  db:
    image: postgres:17.5-bullseye
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nextpruek
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_SERVER_MODE: "True"
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - ":5050:80"
    networks:
      - backend-network
    depends_on:
      - db
  
  backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network: