FROM node:22-slim

WORKDIR /app
RUN apt-get update && apt-get install -y libssl3 netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY .env.development ./

RUN npm install
RUN npm install -g ts-node-dev

COPY . .

ENV PRISMA_CLI_QUERY_ENGINE_TYPE=library
RUN npm run prisma:generate

EXPOSE 3000

ENTRYPOINT ["./docker-entrypoint.sh"]