name: Deploy NestJS to server

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
        
    - name: Build Docker image
      run: docker build -t devops-project:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker tag devops-project:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker rm -f nextpruek
          docker rmi -f ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
          docker run -d \
            --name nextpruek \
            --network backend-network \
            --env-file .env.production \
            -e NODE_ENV=production \
            -p 127.0.0.1:3000:3000 \
            ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
